# Generated by Django 3.0.4 on 2020-03-26 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200326_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 16, 35, 14, 475684), verbose_name='date published'),
        ),
    ]
